### ISSUE TITLE
Refactoring PR

### ISSUE THREAD

**Issue by black7375** [d2phap/fluent-ui#5]
I was impressed with your project and did some refactoring.

**Changes**
- Use Typescript
- Modulize:  For example,  `applyEffect` is close to 150 lines now)
- API applied to single element(`applySingleEffect`): I made it for personal needs, and the main use case is when a new element is created. https://github.com/black7375/Firefox-UI-Fix/issues/2#issuecomment-843867954 [New Tab Handler]
- Maybe a little optimization: Reduced the number of offsets.

Code is [here](https://gist.github.com/black7375/381950352a76f0336f2abe9eb6b1fff1).
I will prepare PR if you want.

**Comment by d2phap** [comment]
Hi @black7375 
Thanks for your contribution, I was also working on a typescript version in the past few weeks, but I haven't completed yet.

**Comment by black7375** [comment]
I'll submit it within next week.
